### ISSUE TITLE
Parsing problems in FOREST_INPUT.xls file from Garnet

### ISSUE THREAD

**Issue by agitter** [sgosline/OmicsIntegrator#2] opened 2015-06-30 20:51 UTC
When Garnet parses the motif ids in events_to_genes_with_motifsregression_results.xls there are a few problems I've noticed in the resulting events_to_genes_with_motifsregression_results_FOREST_INPUT.xls, which contains individual TFs instead of motifs.

* The integer 1 appears as a TF because the string '.1.' appears in several TF families (motifs): 
![image](https://cloud.githubusercontent.com/assets/3532898/8441450/e4f30e94-1f3d-11e5-9241-a3267c59ac11.png)

* DEC1 and DEC2 are converted to dates by Excel:
![image](https://cloud.githubusercontent.com/assets/3532898/8441462/ff78a2e2-1f3d-11e5-91bd-3bd9001f5c19.png)

* Excel 2013 (Windows) does not recognize the file as a properly formatted .xls file:
![image](https://cloud.githubusercontent.com/assets/3532898/8441533/875feeb8-1f3e-11e5-8f12-328f0e1e97a9.png)

Using .csv or a tab-delimited text file instead of .xls could help with the second and third issue.

**Comment by sgosline** [comment] 2015-06-30 20:57
Ok, I can work on this either later this week or early next week.

**Comment by sgosline** [comment] 2015-07-08 17:53
I fixed the second two issues, but the third issue is not that any TFs have a '.1' in the name. The issue is actually introduced by some 'scrubbing' of identifiers from the TAMO source file, I removed the gene name that has a '.1' in it, as it is not legitimate in any species. This is fixed and will be committed with my latest updates to allow for GPS file parsing.

**Closed by sgosline** 2015-07-08 17:53 UTC
